### PR TITLE
Fix fill in missing ranks

### LINKED ISSUE #4141: Fill in missing ranks
Fill in intermediate recognized ranks as follows, including updating the name parser

### Added Ranks

| rank | suffix /abbr. | new enum | example |
| ---- | ------------ | ---------- | --------- |
| Subphylum | -mycotina | 850 | [Agaricomycotina](https://mushroomobserver.org/names/26965) |
| Subclass | -mycetidae | 750 | [Agaricomycetidae](https://mushroomobserver.org/names/30546) |
| Suborder | -ineae | 650 | [Agaricineae](https://mushroomobserver.org/names/61710) |
| Subfamily | -oideae | 560 | [Leccinoideae](https://mushroomobserver.org/names/50569) |
| Tribe | -eae | 540 | Agariceae | 
| Subtribe | -inae | 520 | [Omphalinae](https://mushroomobserver.org/names/47469) | 
| Series | ser.  | 430 | [Amanita series Validae](https://mushroomobserver.org/names/112153) |

see https://github.com/MushroomObserver/mushroom-observer/issues/3359#issuecomment-4047304764 [ICN Ch. 3](https://www.iaptglobal.org/_functions/code/madrid?m=chIII)

### PR DESCRIPTION
**Pull request by JoeCohen**
Add Series, Subtribe, Subfamily, Suborder, Subclass, and Subphylum.
Resolves #4141

### New ranks — create with correct suffix

NOTE: If the suggested Name already exists, invent a different one with the correct suffic.

- [x] Create a name ending in `-mycotina` (e.g. `Basidiomycotina`) with rank **Subphylum** — verify it saves without error
- [x] Create a name ending in `-mycetidae` (e.g. `Agaricomycetidae`) with rank **Subclass** — verify it saves without error
- [x] Create a name ending in `-ineae` (e.g. `Boletineae`) with rank **Suborder** — verify it saves without error
- [x] Create a name ending in `-oideae` (e.g. `Agaricioideae`) with rank **Subfamily** — verify it saves without error
- [x] Create a name ending in `-eae` (but NOT in `oideae` or `aceae`),  e.g. `Agariceae` with rank **Tribe** — verify it saves without error
- [x] Create a name ending in `-inae` (e.g. `Agaricinae`) with rank **Subtribe** — verify it saves without error
- [x] Create a name like `Amanita ser. Nova` with rank **Series** — verify it saves without error

### New ranks — appear in rank dropdown

- [x] Go to **Create Name** — verify **Subphylum**, **Subclass**, **Suborder**, **Subfamily**, **Tribe**, **Subtribe**, and **Series** all appear in the Rank dropdown

### Rank/suffix mismatch — non-admin rejection

- [x] Log in as a regular user (not admin mode)
- [x] Go to **Create Name**, enter `Bolitinae` with rank **Family**, submit — verify **error flash** and name is **not** created
- [x] Enter `Ustilaginomycetes` with rank **Phylum**, submit — verify **error flash** and name is **not** created
- [x] Enter `Agaricales` with rank **Family**, submit — verify **error flash** and name is **not** created

### Rank/suffix mismatch — admin warning then force-create

- [x] Log in as admin (enable admin mode)
- [x] Go to **Create Name**, enter `Bolitinae` with rank **Family**, submit
- [x] Verify a **warning flash** appears (not an error) mentioning the rank mismatch
- [x] Verify the form is redisplayed with `Bolitinae` and rank **Family** still selected
- [x] Submit again without changes — verify `Bolitinae` is created with rank **Family**

### Rank/suffix mismatch — admin warning on edit

- [x] Log in as admin (enable admin mode)
- [x] Navigate to an existing Order-rank name (e.g. Agaricales)
- [x] Change rank to **Family**, submit
- [x] Verify a **warning flash** appears mentioning the rank mismatch
- [x] Verify the form is redisplayed with rank **Family** still selected
- [x] Submit again — verify the name is saved with rank **Family**

### Rank/suffix match — no warning for correct rank

- [x] Log in as admin (enable admin mode)
- [x] Go to **Create Name**, enter `Ustilaginomycota` with rank **Phylum**, submit — verify it saves without any warning

### CODE REVIEW

File: app/models/name/parse.rb [hunk 1]
```diff
@@ -40,15 +41,22 @@ def match?(str)
...
     "Fam." => "Family",
+    "Subtrib." => "Subtribe",
+    "Subord." => "Suborder",
     "Ord." => "Order",
+    "Subcl." => "Subclass",
     "Cl." => "Class",
-    "Phy." => "Plylum"
+    "Subphyl." => "Subphylum",
+    "Phy." => "Phylum"
   }.freeze
```
Comment (JoeCohen) [inline app/models/name/parse.rb:53]: @mo-nathan: Please review the updates to `PROV_RANKS`. 
(I haven't had time to understand the purpose of that constant.)

File: app/models/name/parse.rb [hunk 2]
```diff
@@ -58,16 +66,22 @@ def match?(str)
...
     RankMatcher.new("Subgenus",   / subg\. /),
     RankMatcher.new("Species",    / /),
+    RankMatcher.new("Subtribe",   /^\S+inae$/),
+    RankMatcher.new("Subfamily",  /^\S+oideae$/),
     RankMatcher.new("Family",     /^\S+aceae$/),
-    RankMatcher.new("Family",     /^\S+ineae$/), # :Suborder
+    RankMatcher.new("Suborder",   /^\S+ineae$/),
+    # Tribe (-eae) must follow Family (-aceae), Subfamily (-oideae), and
+    # Suborder (-ineae) because all three endings also end in -eae.
+    RankMatcher.new("Tribe",      /^\S+eae$/),
```
Comment (JoeCohen) [inline app/models/name/parse.rb:80]: @mo-nathan Alternatively, I think I could put the Tribe matcher in between Subtrive and Subfamily by using a negative look-behind. 
Thoughts?

File: CLAUDE.md [hunk 3]
```diff
@@ -44,6 +44,9 @@ bin/rails test test/models/observation_test.rb
 # Run single test by name (use -n flag, NOT RSpec-style syntax)
 bin/rails test test/models/observation_test.rb -n test_scope_needs_naming
 
+# Run multiple specific tests — use a regex; multiple -n flags drop all but last
+bin/rails test test/models/name_test.rb -n /test_name_(spaceship_operator|sort_order)/
+
```
Comment (JoeCohen) [inline CLAUDE.md:49]: Claude kept trying to do this without a regexp, then had to do it right.

File: app/controllers/names_controller.rb [hunk 4]
```diff
@@ -525,13 +539,40 @@ def parse_name
...
+  end
+
+  def raise_rank_mismatch_or_invalid(text_name, in_rank, in_str)
+    guessed = Name.guess_rank(text_name)
+    if guessed && guessed != "Genus" && guessed != in_rank
+      raise(rank_mismatch_error(text_name, in_rank, guessed))
+    end
+
+    raise(:runtime_invalid_for_rank.t(rank: :"rank_#{in_rank.to_s.downcase}",
+                                      name: in_str))
```
[the remark this answers is not in the document]
Comment (JoeCohen) [reply app/controllers/names_controller.rb:562]: Won't do. CC says:
The concern is technically coherent but doesn't apply here. The text_name parameter flowing into raise_rank_mismatch_or_invalid comes directly from params[:name][:text_name] — the form field where the user types a bare name like Bolitinae or Agaricales. Users don't enter provisional rank prefixes (Ord., Fam.) in that field; those are internal parsing tokens used by parse_genus_or_up when the name is assembled into a full string and re-parsed. By the time the suffix-mismatch check runs, the provisional prefix has already been stripped and used to determine rank — it never appears in text_name.

So guess_rank(text_name) here is operating on exactly the input it was designed for: a single-word higher-rank name with a diagnostic suffix. The misleading-warning scenario Copilot describes would require a user to type Ord. Agaricales into the text name box, which the form doesn't prompt for and which would fail earlier validation anyway.

**Comment by JoeCohen** [comment]
Where should groups sort in a Name search? [With species (current)](http://localhost:3000/names?q%5Bdeprecated%5D=false&q%5Bmodel%5D=Name&q%5Bnames%5D%5Binclude_subtaxa%5D=true&q%5Bnames%5D%5Binclude_synonyms%5D=false&q%5Bnames%5D%5Blookup%5D%5B%5D=Gyromitra&q%5Brank%5D%5B%5D=Genus&q%5Brank%5D%5B%5D=Species) vs all groups before any species?
I like what it does currently.

**Comment by mo-nathan** [comment]
> Where should groups sort in a Name search? [With species (current)](http://localhost:3000/names?q%5Bdeprecated%5D=false&q%5Bmodel%5D=Name&q%5Bnames%5D%5Binclude_subtaxa%5D=true&q%5Bnames%5D%5Binclude_synonyms%5D=false&q%5Bnames%5D%5Blookup%5D%5B%5D=Gyromitra&q%5Brank%5D%5B%5D=Genus&q%5Brank%5D%5B%5D=Species) vs all groups before any species? I like what it does currently.

Sorting groups with species seems reasonable in Name search.  I would not in general expect the sort to be heavily impacted by rank.

File: app/models/name/parse.rb (hunk 1 above)
Comment (mo-nathan) [reply app/models/name/parse.rb:53]: PROV_RANKS is for provisional/temporary genera and species.  E.g., https://mushroomobserver.org/names/116050 (Gen. ‘Hemimycena3’).  I think these are very much edge cases and this seems fine.  We can address it later if anyone complains about them.

File: app/models/name/parse.rb (hunk 2 above)
Comment (mo-nathan) [reply app/models/name/parse.rb:80]: I don't fully understand the issue here, but it sounds complicated.  As long as you have some tests and they pass, I don't think the details have much if any practical impact.

**Review by mo-nathan — APPROVED** [review]
Looks good.  Thanks for all this work!

File: app/models/name/parse.rb (hunk 2 above)
Comment (JoeCohen) [reply app/models/name/parse.rb:80]: Issue: The Tribe termination is `eae`, but there are 3 other ranks whose termination includes `eaae`.
So we can correctly parse Tribe's by:
- finding the other ones first, which lets us use a simpler and faster regexp for Tribe, but creates a dependency;
- using an order-independent regexp for Tribe, which is more complicated and slower.

**Comment by JoeCohen** [comment]
thanks for he review. Greatly appreciated.
