### PR TITLE
UTF8 character sets

### LINKED ISSUE #1808: Sequence Notes caron
Certain string values in Sequence Notes cause `Mysql2::Error: Incorrect string value`. See example below.
###Tasks
- [x] Find short string that provokes the error
- [x] Write test (Red)
- [x] Make test Green
- [x] Rubocop
- [x] PR

### PR DESCRIPTION
**Pull request by JoeCohen**
- Changes Articles and Sequences  default character sets  to `utf8mb4`  from `latin1`.  (They the only tables that used a latin charset.)
- Fixes #1808

### CODE REVIEW

File: db/migrate/20240117180824_latin1_to_utf8.rb [hunk 1]
```diff
@@ -0,0 +1,15 @@
+class Latin1ToUtf8 < ActiveRecord::Migration[7.1]
+  def up
+    Article.connection.
+      execute("ALTER TABLE articles CONVERT TO CHARACTER SET utf8mb4;")
+    Sequence.connection.
+      execute("ALTER TABLE sequences CONVERT TO CHARACTER SET utf8mb4;")
```
Comment (JoeCohen) [inline db/migrate/20240117180824_latin1_to_utf8.rb:6]: 1. Should I have separate migrations for Article and Sequence?
2. Is is possible to do this without SQL, for instance using `:options`? I couldn't figure out how.

File: db/migrate/20240117180824_latin1_to_utf8.rb [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+  end
+
+  def down
+    Article.connection.
+      execute("ALTER TABLE articles CONVERT TO CHARACTER SET latin1;")
+    Sequence.connection.
+      execute("ALTER TABLE sequences CONVERT TO CHARACTER SET latin1;")
+  end
```
Comment (JoeCohen) [inline db/migrate/20240117180824_latin1_to_utf8.rb:14]: I should probably delete the down migration. It was OK for testing purposes.
But it will blow up if either of these tables has a single non-latin character.

File: db/migrate/20240117180824_latin1_to_utf8.rb [hunk 3]
```diff
@@ -0,0 +1,15 @@
+class Latin1ToUtf8 < ActiveRecord::Migration[7.1]
+  def up
```
Comment (JoeCohen) [inline db/migrate/20240117180824_latin1_to_utf8.rb:2]: 1. Should I have separate migrations for Article and Sequence?
2. Is is possible to write this migration this without SQL, for instance using `:options`? I couldn't figure out how.

File: db/migrate/20240117180824_latin1_to_utf8.rb [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+    Article.connection.
+      execute("ALTER TABLE articles CONVERT TO CHARACTER SET utf8mb4;")
```
Comment (JoeCohen) [inline db/migrate/20240117180824_latin1_to_utf8.rb:4]: Comment: MySQL recommends utf8mb4.  See https://dev.mysql.com/blog-archive/mysql-8-0-when-to-use-utf8mb3-over-utf8mb4/
Maybe I should make it the db default.

File: db/migrate/20240117180824_latin1_to_utf8.rb (hunk 3 above)
Comment (nimmolo) [reply db/migrate/20240117180824_latin1_to_utf8.rb:2]: Since this is a hot fix, I vote to do both migrations in one. I don't think it can be done without SQL, and from what i can tell from a quick search this seems like it would be valid SQL for any other db we might use.

File: db/migrate/20240117180824_latin1_to_utf8.rb (hunk 4 above)
Comment (nimmolo) [reply db/migrate/20240117180824_latin1_to_utf8.rb:4]: Yes, I vote to make it the db default.

File: db/migrate/20240117180824_latin1_to_utf8.rb (hunk 2 above)
Comment (nimmolo) [reply db/migrate/20240117180824_latin1_to_utf8.rb:14]: Sounds right to me.

**Review by nimmolo — APPROVED** [review]

File: db/migrate/20240117180824_latin1_to_utf8.rb (hunk 4 above)
Comment (JoeCohen) [reply db/migrate/20240117180824_latin1_to_utf8.rb:4]: I'll do that in another PR. 
It's probably safe, but I'd like to think about its consequences.
