### PR TITLE
Fix subject of email to webmaster re Name created

### LINKED ISSUE #3463: Name created email subject
Issue description and proposed solution:
https://mushroomobserver.slack.com/archives/C040TH9FV/p1763051815840199.

Could it be tested by adding an assertion to `test/jobs/inat_import_job_test.rb#test_import_job_infra_specific_name`?

### PR DESCRIPTION
**Pull request by JoeCohen**
Resolves #3463

### CODE REVIEW

File: test/jobs/inat_import_job_test.rb [hunk 1]
```diff
@@ -472,6 +473,14 @@ def test_import_job_create_prov_name
                  proposed_name_notes)
 
     assert(obs.sequences.one?, "Obs should have one sequence")
+
+    email = QueuedEmail.first
+    expected_subject = "#{@user.login} created #{name.text_name}"
+    assert_equal(
```
Comment (JoeCohen) [inline test/jobs/inat_import_job_test.rb]: I put the test in InatImportJobTest because

- it was the importer which exposed the bug
- it was easy -- this method is creating a name
- I didn't want to take the time to figure out another place to put this.

**Comment by JoeCohen** [comment]
In theory, I like option 1.
A VSCode search for "create!" in test returned 103 hits.
Can we implement option 1 in pieces?
Maybe we should discuss in Slack or at the Tech meeting.

**Comment by mo-nathan** [comment]
I created another approach here: https://github.com/MushroomObserver/mushroom-observer/pull/3490.  The issue is tests were making `Name`s without `User`s.  Replacing `create!` with `create` is probably wrong.
