### PR TITLE
Fix parsing string which ends with nbsp

### LINKED ISSUE #3396: iNat import text_name for nil
Image

### PR DESCRIPTION
**Pull request by JoeCohen**
Resolves #3396

### CODE REVIEW

File: app/models/name/parse.rb [hunk 1]
```diff
@@ -590,7 +590,11 @@ def clean_incoming_string(str)
       gsub(/‘|’/, "'").
       delete("\u2028"). # Unicode RLE that we see occasionally as line separator
       gsub(/\s+/, " ").
-      strip_squeeze
+      strip_squeeze.
+      # remove trailing spacing characters including non-breaking spaces
+      sub(/[\s\u00A0\u202F]+\z/, "").
```
Comment (JoeCohen) [inline app/models/name/parse.rb]: CoPilot suggested `u202F` the unicode narrow nonbreaking space.

File: app/models/name/parse.rb [hunk 2]
```diff
@@ -590,7 +590,11 @@ def clean_incoming_string(str)
...
+      # and the same for leading
+      sub(/\A[\s\u00A0\u202F]+/, "")
```
Comment (JoeCohen) [inline app/models/name/parse.rb]: @nwilson-eol: I think we should do the same thing for the beginning of the string.
Does that makes sense?
If so, should I add a test for that?
Also, what about the middle of the incoming string. (I left that as is because I don't think a nonbreaking space in the middle will break anything.)

File: test/models/name_test.rb [hunk 3]
```diff
@@ -1297,6 +1297,22 @@ def test_name_prov_name_with_spaces
     )
   end
 
+  def test_name_prov_name_with_trailing_nonbreaking_space
+    do_name_parse_test(
+      "Cuphophyllus \"pratensis-IN01\"\u00A0",
```
Comment (mo-nathan) [inline test/models/name_test.rb]: I'd include a leading nonbreaking space as well and perhaps even one between the genus and the provisional species name if you take my above recommendation.

**Review by mo-nathan — CHANGES_REQUESTED** [review]
The only thing I'd definitely like to see is for the test to also include a leading non-breaking space.  The idea of dealing with internal non-breaking spaces is not a blocker, but it seems worth attempting.

**Comment by JoeCohen** [comment]
Thanks for the review and the suggestions. I'm in a meeting now, so will implement them after the meeting or tomorrow.

**Comment by JoeCohen** [comment]
The internal one seems easy (at least at first glance).

File: app/models/name/parse.rb [hunk 4]
```diff
@@ -589,7 +589,8 @@ def clean_incoming_string(str)
       gsub(/“|”/, '"'). # let RedCloth format quotes
       gsub(/‘|’/, "'").
       delete("\u2028"). # Unicode RLE that we see occasionally as line separator
-      gsub(/\s+/, " ").
+      # normalize whitespace characters including non-breaking spaces
+      gsub(/([\t\r\n\f\v\u00A0\u202F]+)/, " ").
```
[the remark this answers is not in the document]
Comment (JoeCohen) [reply app/models/name/parse.rb]: @mo-nathan: What do you think? I'm good either way.
I did it this way 

- to avoid substituting a single space for a single space (the most likely event); and
- `strip_squeeze` will take care of the squeezing.

**Review by mo-nathan — APPROVED** [review]
Looks great!  Thanks for the additional changes.
