### PR TITLE
Refresh user stats dry run

### LINKED ISSUE #2046: refresh_all_user_stats Argument Error
Fix this error, which I seem to see daily
>Cron Daemon <root@mushroomobserver.org> Tue, Mar 19, 2024 at 10:14 PM
To: webmaster@mushroomobserver.org
`/var/web/mo/app/models/user_stats.rb:186`:in `refresh_all_user_stats`: wrong number of arguments (given 1, expected 0) (ArgumentError)
 from `script/refresh_caches:55`:in `progress`
 from `script/refresh_caches:78`:in `<main>`

### PR DESCRIPTION
**Pull request by JoeCohen**
- Applies @pellaea's fix for #2046 by adding a `dry_run` keyword parameter to UserStats#refresh_all_user_stats. (It defaults to `false`).

### CODE REVIEW

File: app/models/user_stats.rb [hunk 1]
```diff
@@ -183,7 +183,9 @@ def get_applicable_field(obj)
     # until all records have a value for each column except id and user_id.
     # At the end, we find the existing user_stats record id by user_id, and
     # add in the id and user_id, and update all records at once.
-    def refresh_all_user_stats
+    def refresh_all_user_stats(dry_run: false)
+      return if dry_run
+
```
Comment (nimmolo) [inline app/models/user_stats.rb:188]: @JoeCohen I'm going to alter so that it returns messages like the other "refreshers"

File: test/models/user_stats_test.rb [hunk 2]
```diff
@@ -80,6 +80,36 @@ def test_refresh_all_user_stats
...
+    assert_equal(0, new_rolf_stats.names)
+    assert_equal(0, new_rolf_stats.name_description_authors)
+    assert_equal(0, new_rolf_stats.name_description_editors)
+    assert_equal(0, new_rolf_stats.name_versions)
+    assert_equal(0, new_rolf_stats.namings)
+    assert_equal(0, new_rolf_stats.observations)
+    assert_equal(0, new_rolf_stats.species_lists)
+    assert_equal(0, new_rolf_stats.votes)
+  end
+
```
Comment (nimmolo) [inline test/models/user_stats_test.rb:112]: Thanks for the test!
